CodeSystem: SKS
Title: "Sundhedsvæsenets klassifikationssystem (SKS)"
Description: "Sundhedsvæsenets klassifikationssystem (SKS) - Udvalgte koder i RKKP. Link: urn:oid:1.2.208.176.2.4"

* ^identifier[0].system = "urn:ietf:rfc:3986"
* ^identifier[0].value = "urn:oid:1.2.208.176.2.4"
* ^status = #active
* ^publisher = "RKKP"
* ^date = "2025-07-10T00:00:00+02:00"
* ^contact[0].telecom[0].system = #url
* ^contact[0].telecom[0].value = "https://www.rkkp.dk/"
* ^content = #fragment

* ^property[0].uri = "http://hl7.org/fhir/concept-properties#comment"
* ^property[=].type = #string
* ^property[=].description = "A string that provides additional detail pertinent to the use or understanding of the concept"
* ^property[=].code = #comment

* ^property[+].uri = "http://hl7.org/fhir/concept-properties#effectiveDate"
* ^property[=].type = #dateTime
* ^property[=].description = "The date at which the concept status was last changed"
* ^property[=].code = #effectiveDate

* ^property[+].uri = "http://hl7.org/fhir/concept-properties#status"
* ^property[=].type = #code
* ^property[=].description = "A code that indicates the status of the concept. Typical values are active, experimental, deprecated, and retired"
* ^property[=].code = #status

* ^property[+].uri = "http://hl7.org/fhir/concept-properties#inactive"
* ^property[=].type = #boolean
* ^property[=].description = "True if the concept is not considered active - e.g. not a valid concept any more. Property type is boolean, default value is false. Note that the status property may also be used to indicate that a concept is inactive"
* ^property[=].code = #inactive

* #AAF1 "Indlæggelse" "AAF1 - Indlæggelse"
* #AAF2 "Ambulant" "AAF2 - Ambulant"
* #AZCD10 "cT0: Primær tumor ikke påvist" "AZCD10 - cT0: Primær tumor ikke påvist"
* #AZCD12 "cTis: Carcinoma in situ" "AZCD12 - cTis: Carcinoma in situ"
* #AZCD13 "cT1: Primær tumors størrelse/udstrækning" "AZCD13 - cT1: Primær tumors størrelse/udstrækning"
* #AZCD14 "cT2: Primær tumors størrelse/udstrækning" "AZCD14 - cT2: Primær tumors størrelse/udstrækning"
* #AZCD15 "cT3: Primær tumors størrelse/udstrækning" "AZCD15 - cT3: Primær tumors størrelse/udstrækning"
* #AZCD16 "cT4: Primær tumors størrelse/udstrækning" "AZCD16 - cT4: Primær tumors størrelse/udstrækning"
  * #AZCD16A "cT4a: Primær tumors størrelse/udstrækning" "AZCD16A - cT4a: Primær tumors størrelse/udstrækning"
  * #AZCD16B "cT4b: Primær tumors størrelse/udstrækning" "AZCD16B - cT4b: Primær tumors størrelse/udstrækning"
  * #AZCD16C "cT4c: Primær tumors størrelse/udstrækning" "AZCD16C - cT4c: Primær tumors størrelse/udstrækning"
  * #AZCD16D "cT4d: Primær tumors størrelse/udstrækning" "AZCD16D - cT4d: Primær tumors størrelse/udstrækning"
  * #AZCD16E "cT4e: Primær tumors størrelse/udstrækning" "AZCD16E - cT4e: Primær tumors størrelse/udstrækning"
* #AZCD19 "cTx: Oplysning om tumors størrelse foreligger ikke i afd." "AZCD19 - cTx: Oplysning om tumors størrelse foreligger ikke i afd."
* #AZCD30 "cN0: Ingen regionale lymfeknudemetastaser" "AZCD30 - cN0: Ingen regionale lymfeknudemetastaser"
* #AZCD31 "cN1: Regional lymfeknudemetastase" "AZCD31 - cN1: Regional lymfeknudemetastase"
* #AZCD32 "cN2: Regional lymfeknudemetastase" "AZCD32 - cN2: Regional lymfeknudemetastase"
* #AZCD33 "cN3: Regional lymfeknudemetastase" "AZCD33 - cN3: Regional lymfeknudemetastase"
* #AZCD39 "cNx: Opl om regional lymfeknudestatus foreligger ikke i afd" "AZCD39 - cNx: Opl om regional lymfeknudestatus foreligger ikke i afd"
* #AZCD40 "cM0: Ingen fjernmetastaser" "AZCD40 - cM0: Ingen fjernmetastaser"
* #AZCD41 "cM1: Fjernmetastase" "AZCD41 - cM1: Fjernmetastase"
  * #AZCD41C "cM1c: Fjernmetastase" "AZCD41C - cM1c: Fjernmetastase"
* #BOHJ1 "Behandling med antistoffer" "Behandling med antistoffer"
* #BOQA "Behandling med blodtransfusion" "Behandling med blodtransfusion"
* #BOQF0 "Autolog knoglemarvstransplantation" "BOQF0 - Autolog knoglemarvstransplantation"
* #BOQF1 "Allogen knoglemarvstransplantation" "BOQF1 - Allogen knoglemarvstransplantation"
* #BOQF2 "Non myeloablativ knoglemarvstransplantation (mini-KMT)" "BOQF2 - Non myeloablativ knoglemarvstransplantation (mini-KMT)"
* #BWG "Strålebehandling" "BWG - Strålebehandling"
* #BWHA "Cytostatisk behandling" "Cytostatisk behandling"
  * #BWHA119 "Behandling med cyclophosphamid+doxorubicin+vinkristin+prednisolon (CHOP)" "Behandling med cyclophosphamid+doxorubicin+vinkristin+prednisolon (CHOP)"
  * #BWHA120 "Behandling med MIME" "Behandling med MIME"
  * #BWHA134 "Behandling med cyclophosphamid+vinkristin+prednisolon (CVP) (COP)" "Behandling med cyclophosphamid+vinkristin+prednisolon (CVP) (COP)"
  * #BWHA137 "Behandling med mitoxantron+vinkristin+prednisolon (NOP)" "Behandling med mitoxantron+vinkristin+prednisolon (NOP)"
  * #BWHA138 "Behandling med BEACOPP" "Behandling med BEACOPP"
  * #BWHA156 "Behandling med cyclophosphamid+procarbazin+vinkristin+prednisolon (COPP)" "Behandling med cyclophosphamid+procarbazin+vinkristin+prednisolon (COPP)"
  * #BWHA164 "Behandling med cyclophosphamid+etoposid+vinkristin+prednisolon (CEOP)" "Behandling med cyclophosphamid+etoposid+vinkristin+prednisolon (CEOP)"
  * #BWHA165 "Behandling med cyclophosphamid+doxorubicin+vinkristin+etoposid+prednisolon (CHOEP)" "Behandling med cyclophosphamid+doxorubicin+vinkristin+etoposid+prednisolon (CHOEP)"
  * #BWHA166 "Behandling med cyclophosphamid+mitoxantron+vinkristin+prednisolon (CNOP)" "Behandling med cyclophosphamid+mitoxantron+vinkristin+prednisolon (CNOP)"
  * #BWHA167 "Behandling med doxyrubicin+bleomycin+vinblastin+dacarbazin (ABVD)" "Behandling med doxyrubicin+bleomycin+vinblastin+dacarbazin (ABVD)"
  * #BWHA168 "Behandling med klorambucil+vinblastin+procarbazin+prednisolon (LVPP)" "Behandling med klorambucil+vinblastin+procarbazin+prednisolon (LVPP)"
  * #BWHA258 "Behandling med cylophosphamid+doxorubicin+vinkristin+prednisolon eskaleret dosis (maxiCHOP)" "Behandling med cylophosphamid+doxorubicin+vinkristin+prednisolon eskaleret dosis (maxiCHOP)"
  * #BWHA309 "Behandling med højdosis melfalan (konditionering)" "BWHA309 - Behandling med højdosis melfalan (konditionering)"
  * #BWHA310 "Behandling med BEAM (konditionering)" "Behandling med BEAM (konditionering)"
* #DC15 "Kræft i spiserøret" "Kræft i spiserøret"
* #DC16 "Kræft i mavesækken" "Kræft i mavesækken"
* #DC17 "Kræft i tyndtarmen" "Kræft i tyndtarmen"
* #DC22 "Kræft i leveren og intrahepatiske galdegange" "Kræft i leveren og intrahepatiske galdegange"
* #DC25 "Kræft i bugspytkirtlen" "Kræft i bugspytkirtlen"
* #DC32 "Kræft i strubehovedet" "Kræft i strubehovedet"
* #DC43 "Modermærkekræft i huden" "Modermærkekræft i huden"
* #DC50 "Brystkræft" "Brystkræft"
* #DC53 "Kræft i livmoderhalsen" "Kræft i livmoderhalsen"
* #DC61 "Kræft i blærehalskirtlen" "Kræft i blærehalskirtlen"
* #DC62 "Testikelkræft" "Testikelkræft"
* #DC67 "Kræft i urinblæren" "Kræft i urinblæren"
* #DC64-DC66 "Kræft i nyre, nyrebækken og urinleder" "Kræft i nyre, nyrebækken og urinleder"
* #DC73 "Kræft i skjoldbruskkirtlen" "Kræft i skjoldbruskkirtlen"
* #DC81 "Hodgkin lymfomer" "Hodgkin lymfomer"
* #DC90 "Maligne plasmacelle neoplasier" "Maligne plasmacelle neoplasier"
* #DC18 "Kræft i tyktarmen" "Kræft i tyktarmen"
  * #DC180 "Kræft i caecum" "Kræft i caecum"
  * #DC182 "Kræft i colon ascendens" "Kræft i colon ascendens"
  * #DC183 "Kræft i flexura coli dextra" "Kræft i flexura coli dextra"
  * #DC184 "Kræft i colon transversum" "Kræft i colon transversum"
  * #DC185 "Kræft i flexura coli sinistra" "Kræft i flexura coli sinistra"
  * #DC186 "Kræft i colon descendens" "Kræft i colon descendens"
  * #DC187 "Kræft i colon sigmoideum" "Kræft i colon sigmoideum"
  * #DC189 "Kræft i tyktarmen UNS" "Kræft i tyktarmen UNS"
* #DC20 "Kræft i endetarmen" "Kræft i endetarmen"
* #DC780 "Fjernmetastase i lunge" "Fjernmetastase i lunge"
* #DC786B "Metastase i peritoneum" "DC786B - Metastase i peritoneum"
* #DC787 "Fjernmetastase i leveren" "Fjernmetastase i leveren"
* #DC798D "Fjernmetastase UNS" "Fjernmetastase UNS"
* #DI110 "Hypertensiv hjertesygdom med inkompenseret hjertesvigt" "DI110 - Hypertensiv hjertesygdom med inkompenseret hjertesvigt"
* #DI130 "Hypertensiv hjertesygdom og nyresygdom med hjertesvigt" "DI130 - Hypertensiv hjertesygdom og nyresygdom med hjertesvigt"
* #DI132 "Hypertensiv hjertesygdom og nyresygdom med hjertesvigt og nyresvigt" "DI132 - Hypertensiv hjertesygdom og nyresygdom med hjertesvigt og nyresvigt"
* #DI420 "Dilateret kardiomyopati" "DI420 - Dilateret kardiomyopati"
* #DI426 "Alkoholisk kardiomyopati" "DI426 - Alkoholisk kardiomyopati"
* #DI427 "Kardiomyopati forårsaget af lægemiddel eller andet agens" "DI427 - Kardiomyopati forårsaget af lægemiddel eller andet agens"
* #DI429 "Kardiomyopati UNS" "DI429 - Kardiomyopati UNS"
* #DI500 "Kronisk hjerteinsufficiens" "DI500 - Kronisk hjerteinsufficiens"
* #DI501 "Venstresidig hjerteinsufficiens" "DI501 - Venstresidig hjerteinsufficiens"
  * #DI501B "Kardielt lungeødem" "DI501B - Kardielt lungeødem"
* #DI509 "Hjertesvigt UNS" "DI509 - Hjertesvigt UNS"
* #DI60 "Subaraknoidalblødning" "DI60 - Subaraknoidalblødning"
* #DI61 "Hjerneblødning" "DI61 - Hjerneblødning"
* #DI63 "Hjerneinfarkt" "DI63 - Hjerneinfarkt"
  * #DI630 "Hjerneinfarkt forårsaget af trombose i præcerebral arterie" "DI630 - Hjerneinfarkt forårsaget af trombose i præcerebral arterie"
  * #DI631 "Hjerneinfarkt forårsaget af emboli i præcerebral arterie" "DI631 - Hjerneinfarkt forårsaget af emboli i præcerebral arterie"
  * #DI632 "Hjerneinfarkt forårsaget af tillukning eller stenose i præcerebral arterie UNS" "DI632 - Hjerneinfarkt forårsaget af tillukning eller stenose i præcerebral arterie UNS"
  * #DI633 "Hjerneinfarkt forårsaget af trombose i cerebral arterie" "DI633 - Hjerneinfarkt forårsaget af trombose i cerebral arterie"
  * #DI634 "Hjerneinfarkt forårsaget af emboli i cerebral arterie" "DI634 - Hjerneinfarkt forårsaget af emboli i cerebral arterie"
  * #DI635 "Hjerneinfarkt forårsaget af tillukning eller stenose i cerebral arterie UNS" "DI635 - Hjerneinfarkt forårsaget af tillukning eller stenose i cerebral arterie UNS"
  * #DI638 "Anden form for hjerneinfarkt" "DI638 - Anden form for hjerneinfarkt"
  * #DI639 "Hjerneinfarkt UNS" "DI639 - Hjerneinfarkt UNS"
* #DI64 "Slagtilfælde uden oplysning om blødning eller infarkt" "DI64 - Slagtilfælde uden oplysning om blødning eller infarkt"
* #DG45 "Transitorisk cerebral iskæmi og beslægtede syndromer" "DG45 - Transitorisk cerebral iskæmi og beslægtede syndromer"
* #DK40 "Lyskebrok" "DK40 - Lyskebrok"
* #DK41 "Lårbrok" "DK41 - Lårbrok"
* #KJFB20 "Ileocækal resektion" "KJFB20 - Ileocækal resektion"
* #KJFB30 "Højresidig hemikolektomi" "KJFB30 - Højresidig hemikolektomi"
  * #KJFB30A "Udvidet højresidig hemikolektomi" "KJFB30A - Udvidet højresidig hemikolektomi"
* #KJFB34 "Anden laparoskopisk samtidig resektion af tyndtarm og tyktarm" "KJFB34 - Anden laparoskopisk samtidig resektion af tyndtarm og tyktarm"
* #KJFB40 "Resektion af colon transversum" "KJFB40 - Resektion af colon transversum"
* #KJFB43 "Venstresidig hemikolektomi" "KJFB43 - Venstresidig hemikolektomi"
* #KJFB46 "Resektion af colon sigmoideum" "KJFB46 - Resektion af colon sigmoideum"
* #KJFB50 "Anden colonresektion" "KJFB50 - Anden colonresektion"
* #KJFB53 "Resektion af venstre fleksur" "KJFB53 - Resektion af venstre fleksur"
* #KJFB60 "Resektion af colon sigmoideum med kolostomi" "KJFB60 - Resektion af colon sigmoideum med kolostomi"
* #KJFB63 "Anden tyktarmsresektion med kolostomi og distal lukning" "KJFB63 - Anden tyktarmsresektion med kolostomi og distal lukning"
* #KJFH00 "Kolektomi og ileorektostomi" "KJFH00 - Kolektomi og ileorektostomi"
* #KJFH10 "Kolektomi og ileostomi" "KJFH10 - Kolektomi og ileostomi"
* #KJFH20 "Proktokolektomi og ileostomi" "KJFH20 - Proktokolektomi og ileostomi"
* #KJGB00 "Resektion af endetarm" "KJGB00 - Resektion af endetarm"
* #KJGB10 "Resektion af endetarm med kolostomi" "KJGB10 - Resektion af endetarm med kolostomi"
* #KJGB32 "Abdominal og intersphincterisk excision af endetarm" "KJGB32 - Abdominal og intersphincterisk excision af endetarm"
* #KJGB35 "Abdominal og ischioanal excision af endetarm" "KJGB35 - Abdominal og ischioanal excision af endetarm"
* #KJGB36 "Abdominal og ekstralevatorisk excision af endetarm" "KJGB36 - Abdominal og ekstralevatorisk excision af endetarm"
* #KJAH00 "Eksplorativ laparotomi" "KJAH00 - Eksplorativ laparotomi"
* #KJMA "Splenektomier" "KJMA - Splenektomier"
* #KPAF20 "Trombendarterektomi i a. carotis communis" "KPAF20 - Trombendarterektomi i a. carotis communis"
* #KPAF21 "Trombendarterektomi i a. carotis interna" "KPAF21 - Trombendarterektomi i a. carotis interna"
* #KPAF22 "Trombendarterektomi i a. carotis externa" "KPAF22 - Trombendarterektomi i a. carotis externa"
* #KPAK21 "Reimplantation af a. carotis interna" "KPAK21 - Reimplantation af a. carotis interna"
* #KPAP10 "Perkut. plastik på truncus brachiocephalicus" "KPAP10 - Perkut. plastik på truncus brachiocephalicus"
* #KPAP20 "Perkut. plastik på a. carotis communis" "KPAP20 - Perkut. plastik på a. carotis communis"
* #KPAP21 "Perkut. plastik på a. carotis interna" "KPAP21 - Perkut. plastik på a. carotis interna"
* #KPAP30 "Perkutan plastik på a. subclavia" "KPAP30 - Perkutan plastik på a. subclavia"
* #KPAP99 "Perkut. plastik på an. gren på a. afgå. fra aortabuen" "KPAP99 - Perkut. plastik på an. gren på a. afgå. fra aortabuen"
* #KPBP10 "Perkutan plastik på a. axillaris" "KPBP10 - Perkutan plastik på a. axillaris"
* #KPBP20 "Perkutan plastik på a. brachialis" "KPBP20 - Perkutan plastik på a. brachialis"
* #KPBP99 "Perkut. plastik på anden arterie i overekstremitet" "KPBP99 - Perkut. plastik på anden arterie i overekstremitet"
* #KPBQ10 "Indsættelse af endoprotese i a. axillaris" "KPBQ10 - Indsættelse af endoprotese i a. axillaris"
* #KPBQ20 "Indsættelse af endoprotese i a. brachialis" "KPBQ20 - Indsættelse af endoprotese i a. brachialis"
* #KPBQ99 "Indsættelse af endoprotese i anden arterie i overekstremitet" "KPBQ99 - Indsættelse af endoprotese i anden arterie i overekstremitet"
* #KPCG10 "Aneurismeoperation på supracøliakale el. jukstarenale ao." "KPCG10 - Aneurismeoperation på supracøliakale el. jukstarenale ao."
* #KPCP10 "Perkutan plastik på suprarenale aorta" "KPCP10 - Perkutan plastik på suprarenale aorta"
* #KPCP20 "Perkut. plastik på truncus coeliacus el. grene" "KPCP20 - Perkut. plastik på truncus coeliacus el. grene"
* #KPCP30 "Perkut. plastik på a. mesenterica superior" "KPCP30 - Perkut. plastik på a. mesenterica superior"
* #KPCP40 "Perkutan plastik på a. renalis" "KPCP40 - Perkutan plastik på a. renalis"
* #KPCP40A "Perkut. plastik på arterie til transplanteret nyre" "KPCP40A - Perkut. plastik på arterie til transplanteret nyre"
* #KPCP99 "Perkut. plastik på anden visceralarterie" "KPCP99 - Perkut. plastik på anden visceralarterie"
* #KPCQ10 "Inds af endoprotese i supracøliakale el. jukstrarenale aorta" "KPCQ10 - Inds af endoprotese i supracøliakale el. jukstrarenale aorta"
* #KPCQ20 "Indsættelse af endoprotese i truncus coeliacus el. grene" "KPCQ20 - Indsættelse af endoprotese i truncus coeliacus el. grene"
* #KPCQ30 "Indsættelse af endoprotese i a. mesenterica superior" "KPCQ30 - Indsættelse af endoprotese i a. mesenterica superior"
* #KPCQ40 "Indsættelse af endoprotese i a. renalis" "KPCQ40 - Indsættelse af endoprotese i a. renalis"
* #KPCQ99 "Indsættelse af endoprotese i anden visceralarterie" "KPCQ99 - Indsættelse af endoprotese i anden visceralarterie"
* #KPCU83 "Perkut. plastik på byp. fra suprarenale ao. el. viscerala." "KPCU83 - Perkut. plastik på byp. fra suprarenale ao. el. viscerala."
* #KPCU84 "Indsæt. af stent i byp. fra suprarenale ao. el. viscerala." "KPCU84 - Indsæt. af stent i byp. fra suprarenale ao. el. viscerala."
* #KPCW20 "Perkut. translum. fenestrering af suprarenale ao." "KPCW20 - Perkut. translum. fenestrering af suprarenale ao."
* #KPDA10 "Eksploration af infrarenale aorta" "KPDA10 - Eksploration af infrarenale aorta"
* #KPDG10 "Aneurismeoperation på infrarenale aorta" "KPDG10 - Aneurismeoperation på infrarenale aorta"
* #KPDG20 "Aneurismeoperation m. aortoiliakal byp." "KPDG20 - Aneurismeoperation m. aortoiliakal byp."
* #KPDG21 "Aneurismeoperation m. aortobi-iliakal byp." "KPDG21 - Aneurismeoperation m. aortobi-iliakal byp."
* #KPDG22 "Aneurismeop. m. aortoiliakal/kontralat. iliakofemoral byp." "KPDG22 - Aneurismeop. m. aortoiliakal/kontralat. iliakofemoral byp."
* #KPDG23 "Aneurismeoperation m. aortofemoral byp." "KPDG23 - Aneurismeoperation m. aortofemoral byp."
* #KPDG24 "Aneurismeoperation m. aortobifemoral byp." "KPDG24 - Aneurismeoperation m. aortobifemoral byp."
* #KPDP10 "Perkutan plastik på infrarenale aorta" "KPDP10 - Perkutan plastik på infrarenale aorta"
* #KPDP30 "Perkutan plastik på iliaka-arterie" "KPDP30 - Perkutan plastik på iliaka-arterie"
* #KPDQ10 "Indsættelse af endoprotese i infrarenale aorta" "KPDQ10 - Indsættelse af endoprotese i infrarenale aorta"
* #KPDQ20 "Indsættelse af endoprotese aorto-iliakalt" "KPDQ20 - Indsættelse af endoprotese aorto-iliakalt"
* #KPDQ21 "Indsættelse af endoprotese aorto-bi-iliakalt" "KPDQ21 - Indsættelse af endoprotese aorto-bi-iliakalt"
* #KPDU83 "Perkut. plastik på byp. fra infraren. ao. el. iliaka-a." "KPDU83 - Perkut. plastik på byp. fra infraren. ao. el. iliaka-a."
* #KPDU84 "Indsæt. af stent i byp. fra infraren. ao. el. iliaka-a." "KPDU84 - Indsæt. af stent i byp. fra infraren. ao. el. iliaka-a."
* #KPDW20 "Perkut. translum. fenestrering af infrarenale ao." "KPDW20 - Perkut. translum. fenestrering af infrarenale ao."
* #KPEH20 "Byp. fra a. femor. til a. poplit. oven for knæet" "KPEH20 - Byp. fra a. femor. til a. poplit. oven for knæet"
* #KPEH30 "Byp. fra a. femor. til a. poplit. neden for knæet" "KPEH30 - Byp. fra a. femor. til a. poplit. neden for knæet"
* #KPEP10 "Perkut. plastik på a. femoralis communis" "KPEP10 - Perkut. plastik på a. femoralis communis"
* #KPEP11 "Perkut. plastik på a. profunda femoris" "KPEP11 - Perkut. plastik på a. profunda femoris"
* #KPEP12 "Perkut. plastik på a. femoralis superficialis" "KPEP12 - Perkut. plastik på a. femoralis superficialis"
* #KPEQ10 "Indsættelse af endoprotese i a. femoralis communis" "KPEQ10 - Indsættelse af endoprotese i a. femoralis communis"
* #KPEQ11 "Indsættelse af endoprotese i a. profunda femoris" "KPEQ11 - Indsættelse af endoprotese i a. profunda femoris"
* #KPEQ12 "Indsættelse af endoprotese i a. femoralis superficialis" "KPEQ12 - Indsættelse af endoprotese i a. femoralis superficialis"
* #KPEQ99 "An. indsæt. af endoprotese i a. femor. el. dens grene" "KPEQ99 - An. indsæt. af endoprotese i a. femor. el. dens grene"
* #KPEU83 "Perkut. plastik på byp. fra a. femor. til a. poplit." "KPEU83 - Perkut. plastik på byp. fra a. femor. til a. poplit."
* #KPEU84 "Indsæt. af stent i byp. fra a. femor. til a. poplit." "KPEU84 - Indsæt. af stent i byp. fra a. femor. til a. poplit."
* #KPFH20 "Byp. fra a. femor. el. a. poplit. til a. i underben" "KPFH20 - Byp. fra a. femor. el. a. poplit. til a. i underben"
* #KPFH21 "Byp. fra a. femor/poplit. til proks. del af a. tibialis ant." "KPFH21 - Byp. fra a. femor/poplit. til proks. del af a. tibialis ant."
* #KPFH22 "Byp. fra a. femor/poplit. til dist. del af a. tibialis ant." "KPFH22 - Byp. fra a. femor/poplit. til dist. del af a. tibialis ant."
* #KPFH23 "Byp. fra a. femor. el. a. poplit. til trun. tibioperonealis" "KPFH23 - Byp. fra a. femor. el. a. poplit. til trun. tibioperonealis"
* #KPFH24 "Byp. fra a. femor/poplit. til proks. a. tibialis post." "KPFH24 - Byp. fra a. femor/poplit. til proks. a. tibialis post."
* #KPFH25 "Byp. fra a. femor. el. a. poplit. til dist. a. tibialis post" "KPFH25 - Byp. fra a. femor. el. a. poplit. til dist. a. tibialis post"
* #KPFH26 "Byp. fra a. femor. el. a. poplit. til proks. a. peronealis" "KPFH26 - Byp. fra a. femor. el. a. poplit. til proks. a. peronealis"
* #KPFH27 "Byp. fra a. femor. el. a. poplit. til dist. a. peronealis" "KPFH27 - Byp. fra a. femor. el. a. poplit. til dist. a. peronealis"
* #KPFH28 "Byp. fra a. femor. el. a. poplit. til a. dorsalis pedis" "KPFH28 - Byp. fra a. femor. el. a. poplit. til a. dorsalis pedis"
* #KPFH29 "Byp. fra a. femor/poplit. til a. tibialis post. i fod" "KPFH29 - Byp. fra a. femor/poplit. til a. tibialis post. i fod"
* #KPFH99 "An. byp. fra a. femor. el. a. poplit. til a. i underben/fod" "KPFH99 - An. byp. fra a. femor. el. a. poplit. til a. i underben/fod"
* #KPFP10 "Perkutan plastik på a. poplitea" "KPFP10 - Perkutan plastik på a. poplitea"
* #KPFP30 "Perkut. plastik på arterie i underben el. fod" "KPFP30 - Perkut. plastik på arterie i underben el. fod"
* #KPFQ10 "Indsættelse af endoprotese i a. poplitea" "KPFQ10 - Indsættelse af endoprotese i a. poplitea"
* #KPFQ30 "Indsættelse af endoprotese i arterie i underben el. fod" "KPFQ30 - Indsættelse af endoprotese i arterie i underben el. fod"
* #KPFU83 "Perkut. plastik på byp. fra a-fem/poplit. til a-underben/fod" "KPFU83 - Perkut. plastik på byp. fra a-fem/poplit. til a-underben/fod"
* #KPFU84 "Indsæt. stent i byp. fra a. femor/poplit. til a-underben/fod" "KPFU84 - Indsæt. stent i byp. fra a. femor/poplit. til a-underben/fod"
* #KPGU83 "Perkut. plastik på ekstra-anatomisk byp." "KPGU83 - Perkut. plastik på ekstra-anatomisk byp."
* #KPGU84 "Indsættelse af stent i ekstra-anatomisk byp." "KPGU84 - Indsættelse af stent i ekstra-anatomisk byp."
* #T000010 "hud" "T000010 - hud"
* #T000094 "mamma" "T000094 - mamma"
* #T000113 "knoglemarv" "T000113 - konglemarv"
* #T000132 "milt" "T000132 - milt"
* #T000134 "lymfeknude" "T000134 - lymfeknude"
* #T000146 "lymfeknude på hals" "T000146 - lymfeknude på hals"
* #T000148 "supraclaviculær lymfeknude" "T000148 - supraclaviculær lymfeknude"
* #T000154 "infraclaviculær lymfeknude" "T000154 - infraclaviculær lymfeknude"
* #T000165 "Lymfeknude i mediastinum" "T000165 - Lymfeknude i mediastinum"
* #T000166 "Lymfeknude i abdomen" "T000166 - Lymfeknude i abdomen"
* #T000174 "lymfeknude i aksil" "T000174 - lymfeknude i aksil"
* #T000177 "lymfeknude i inguen" "T000177 - lymfeknude i inguen"
* #T000224 "Knogle" "T000224 - Knogle"
* #T000240 "os sacrum" "T000240 - os sacrum"
* #T000241 "os coccygis" "T000241 - os coccygis"
* #T000298 "skeletmuskulatur" "T000298 - skeletmuskulatur"
* #T000347 "cavitas nasi" "T000347 - cavitas nasi"
* #T000352 "Bihule" "T000352 - Bihule"
* #T000398 "lunge" "T000398 - lunge"
* #T000400 "lungehilum" "T000400 - lungehilum"
* #T000438 "Hjerte" "T000438 - Hjerte"
* #T000492 "blodkar" "T000492 - blodkar"
* #T000522 "arteria carotis interna" "T000522 - arteria carotis interna"
* #T000523 "arteria communicans posterior" "T000523 - arteria communicans posterior"
* #T000526 "arteria communicans anterior" "T000526 - arteria communicans anterior"
* #T000527 "arteria cerebri anterior" "T000527 - arteria cerebri anterior"
* #T000528 "arteria cerebri media" "T000528 - arteria cerebri media"
* #T000529 "arteria vertebralis" "T000529 - arteria vertebralis"
* #T000530 "arteria basilaris" "T000530 - arteria basilaris"
* #T000531 "arteria cerebelli" "T000531 - arteria cerebelli"
* #T000569 "mund" "T000569 - mund"
* #T000600 "Spytkirtler" "T000600 - Spytkirtler"
* #T000607 "lever" "T000607 - lever"
* #T000627 "galdeblære" "T000627 - galdeblære"
* #T000638 "pancreas" "T000638 - pancreas"
* #T000647 "Pharynx" "T000647 - Pharynx"
* #T000654 "Ganetonsil" "T000654 - Ganetonsil"
* #T000653 "Tonsil og adenoid" "T000653 - Tonsil og adenoid"
* #T000657 "Ganetonsiller" "T000657 - Ganetonsiller"
* #T000662 "øsofagus" "T000662 - øsofagus"
* #T000670 "ventrikel" "T000670 - ventrikel"
* #T000695 "tyndtarm" "T000695 - tyndtarm"
* #T000702 "mesenterium" "T000702 - mesenterium"
* #T000703 "duodenum" "T000703 - duodenum"
* #T000706 "Tarm" "T000706 - Tarm"
* #T000725 "colon" "T000725 - colon"
* #T000773 "nyre" "T000773 - nyre"
* #T000803 "ureter" "T000803 - ureter"
* #T000812 "vesica urinaria" "T000812 - vesica urinaria"
* #T000824 "urethra" "T000824 - urethra"
* #T000834 "Prostata" "T000834 - prostata"
* #T000840 "vesicula seminalis" "T000840 - vesicula seminalis"
* #T000842 "testis" "T000842 - testis"
* #T000854 "begge testes" "T000854 - begge testes"
* #T000892 "vagina" "T000892 - vagina"
* #T000898 "uterus" "T000898 - uterus"
* #T000909 "Genitalia interna" "T000909 - Genitalia interna"
* #T000948 "begge ovarier" "T000948 - begge ovarier"
* #T001022 "glandula thyroidea" "T001022 - glandula thyroidea"
* #T001039 "centralnervesystem" "T001039 - centralnervesystem"
* #T001057 "arachnoidea" "T001057 - arachnoidea"
* #T001127 "bulbus oculi" "T001127 - bulbus oculi"
* #T001145 "glandula lacrimalis" "T001145 - glandula lacrimalis"
* #T001182 "Orbita" "T001182 - Orbita"
* #T001184 "Hals" "T001184 - Hals"
* #T001210 "mediastinum" "T001210 - mediastinum"
* #T001220 "bugvæg" "T001220 - bugvæg"
* #T001222 "peritoneum" "T001222 - peritoneum"
* #T001227 "retroperitoneum" "T001227 - retroperitoneum"
* #T001231 "Pelvis" "T001231 - Pelvis"
* #TUL1 "højresidig" "TUL1 - højresidig"
* #TUL2 "venstresidig" "TUL2 - venstresidig"
* #TUL3 "dobbeltsidig" "TUL3 - dobbeltsidig"
* #TUL7 "side kan ikke angives" "TUL7 - side kan ikke angives"
* #TUL9A "lateral" "TUL9A - lateral"
* #TUL9B "medial" "TUL9B - medial"
* #ZDA03A1 "Clavien grad 1" "Clavien grad 1"
* #ZDA03A2 "Clavien grad 2" "Clavien grad 2"
* #ZDA03A3 "Clavien grad 3" "Clavien grad 3"
  * #ZDA03A3A "Clavien grad 3a" "Clavien grad 3a"
  * #ZDA03A3B "Clavien grad 3b" "Clavien grad 3b"
* #ZDA03A4 "Clavien grad 4" "Clavien grad 4"
  * #ZDA03A4A "Clavien grad 4a" "Clavien grad 4a"
  * #ZDA03A4B "Clavien grad 4b" "Clavien grad 4b"
* #ZDA03A5 "Clavien grad 5" "Clavien grad 5"
* #ZDI021 "asymptomatisk" "ZDI021 - asymptomatisk"
* #ZDI022 "symptomatisk" "ZDI022 - symptomatisk"

// ---------------------------------------------------------------------------
// SKS codes consolidated from other CodeSystems in this IG.
// Each code below was verified to exist in the authoritative SKS release
// (Sundhedsdatastyrelsen SKScomplete). Displays are the RKKP-curated Danish
// texts from the originating CodeSystem.
// ---------------------------------------------------------------------------

// Merged from MorsDiagnosekoder (Mors Diagnosekoder (DNSL)) — 45 codes
* #DA162 "Lungetuberkulose u angivelse af bakt eller hist verif" "DA162 - Lungetuberkulose u angivelse af bakt eller hist verif"
* #DA188 "Tuberkulose i andre specificerede organer" "DA188 - Tuberkulose i andre specificerede organer"
* #DA419 "Septikæmi uden specifikation" "DA419 - Septikæmi uden specifikation"
* #DB181 "Hepatitis B viralis Chronica u Delta agens" "DB181 - Hepatitis B viralis Chronica u Delta agens"
* #DB182 "Hepatitis C viralis chronica" "DB182 - Hepatitis C viralis chronica"
* #DB188 "Hepatitis viralis Chronica alia" "DB188 - Hepatitis viralis Chronica alia"
* #DB349 "Virusinfektion uden specifikation" "DB349 - Virusinfektion uden specifikation"
* #DB999 "Andre og ikke specificerede infektiøse sygdomme" "DB999 - Andre og ikke specificerede infektiøse sygdomme"
* #DD489 "Neopl uden specifikation og lokalisation" "DD489 - Neopl uden specifikation og lokalisation"
* #DD629 "Akut anæmi efter blødning" "DD629 - Akut anæmi efter blødning"
* #DD729 "Sygdomme i hvide blodlegemer uden specifikation" "DD729 - Sygdomme i hvide blodlegemer uden specifikation"
* #DE875 "Kaliumoverskud" "DE875 - Kaliumoverskud"
* #DE876A "Hypokaliæmi" "DE876A - Hypokaliæmi"
* #DE876A ^property[0].code = #inactive
* #DE876A ^property[0].valueBoolean = true
* #DE877 "Væskeoverskud" "DE877 - Væskeoverskud"
* #DF039 "Demens uden specifikation" "DF039 - Demens uden specifikation"
* #DI219 "Akut myokardieinfarkt (AMI uden specifikation" "DI219 - Akut myokardieinfarkt (AMI uden specifikation"
* #DI269 "Embolia pulmonis u akut cor pulmonale" "DI269 - Embolia pulmonis u akut cor pulmonale"
* #DI461 "Pludselig hjertedød" "DI461 - Pludselig hjertedød"
* #DI649 "Apoplexia cerebri uden specifikation" "DI649 - Apoplexia cerebri uden specifikation"
* #DI772 "Ruptura arteriae" "DI772 - Ruptura arteriae"
* #DJ129 "Viruspneumoni uden specifikation" "DJ129 - Viruspneumoni uden specifikation"
* #DJ159 "Bakteriel pneumoni uden specifikation" "DJ159 - Bakteriel pneumoni uden specifikation"
* #DJ168 "Pneumonier forårsaget af andre specificerede infekt agentia" "DJ168 - Pneumonier forårsaget af andre specificerede infekt agentia"
* #DJ449 "Kronisk obstruktiv lungesygdom uden specifikation" "DJ449 - Kronisk obstruktiv lungesygdom uden specifikation"
* #DK281 "Ulcus gastrojejunale pepticum acutum m perforation" "DK281 - Ulcus gastrojejunale pepticum acutum m perforation"
* #DK550 "Akut karsygdom i tarm" "DK550 - Akut karsygdom i tarm"
* #DK631 "Perforatio intestini non traumatica" "DK631 - Perforatio intestini non traumatica"
* #DK638C "Haemorrhagia tractus gastrointestinalis" "DK638C - Haemorrhagia tractus gastrointestinalis"
* #DK650 "Peritonitis acuta" "DK650 - Peritonitis acuta"
* #DK668 "Sygdom i bughinde, andre specificerede" "DK668 - Sygdom i bughinde, andre specificerede"
* #DK719 "Toksisk leversygdom uden specifikation" "DK719 - Toksisk leversygdom uden specifikation"
* #DK729 "Leversvigt uden specifikation" "DK729 - Leversvigt uden specifikation"
* #DK746 "Cirrhosis hepatis, anden og uden specifikation" "DK746 - Cirrhosis hepatis, anden og uden specifikation"
* #DK859 "Pancreatitis acuta" "DK859 - Pancreatitis acuta"
* #DN188B "Pericarditis, uræmisk" "DN188B - Pericarditis, uræmisk"
* #DN188B ^property[0].code = #inactive
* #DN188B ^property[0].valueBoolean = true
* #DN199 "Uræmi uden specifikation" "DN199 - Uræmi uden specifikation"
* #DQ446 "Hepar cysticum congenitum" "DQ446 - Hepar cysticum congenitum"
* #DR589 "Haemorrhagia uden specifikation" "DR589 - Haemorrhagia uden specifikation"
* #DR649 "Cachexia" "DR649 - Cachexia"
* #DR999 "Mors uden specifkation" "DR999 - Mors uden specifkation"
* #DR999 ^property[0].code = #inactive
* #DR999 ^property[0].valueBoolean = true
* #DT758 "Skader af ydre påvirkninger, andre specificerede" "DT758 - Skader af ydre påvirkninger, andre specificerede"
* #DT810 "Haemorrhagia postop et haematoma postop ikke klas ansted" "DT810 - Haemorrhagia postop et haematoma postop ikke klas ansted"
* #DT824 "Complicatio katherisationis vasorum dialyseos" "DT824 - Complicatio katherisationis vasorum dialyseos"
* #DT888 "Kompl til kir og med beh ikke klass ansted, andre spec" "DT888 - Kompl til kir og med beh ikke klass ansted, andre spec"
* #DZ915 "Selvpåført skade" "DZ915 - Selvpåført skade"

// Merged from ProcedureUroGyn (Procedurer, urogynækologi (DUGS)) — 80 codes
* #BJAA0 "Engangskateterisation af blæren" "BJAA0 - Engangskateterisation af blæren"
* #BJAZ0 "Anlæggelse af blærekateter" "BJAZ0 - Anlæggelse af blærekateter"
* #BJKA02 "Vejledning og undervisning i selvkateterisation" "BJKA02 - Vejledning og undervisning i selvkateterisation"
* #BOQA0 "Blodtransfusion" "BOQA0 - Blodtransfusion"
* #BPH "Systemisk antibiotikabehandling af infektionssygdomme" "BPH - Systemisk antibiotikabehandling af infektionssygdomme"
* #DN393 "Stress-inkontinens" "DN393 - Stress-inkontinens"
* #DN895D "Vaginal striktur" "DN895D - Vaginal striktur"
* #DR102B "Mavesmerter lokaliseret til bækken" "DR102B - Mavesmerter lokaliseret til bækken"
* #DR339D "Residualurin" "DR339D - Residualurin"
* #DR391 "Vandladningsbesvær UNS" "DR391 - Vandladningsbesvær UNS"
* #DR522B "Smerter i kønsorganer" "DR522B - Smerter i kønsorganer"
* #DT810G "Postoperativ blødning UNS" "DT810G - Postoperativ blødning UNS"
* #DT810H "Postoperativt hæmatom UNS" "DT810H - Postoperativt hæmatom UNS"
* #DT812G "Utilsigtet peroperativ punktur eller læsion af gastrointestinalkanalen" "DT812G - Utilsigtet peroperativ punktur eller læsion af gastrointestinalkanalen"
* #DT812H "Utilsigtet peroperativ punktur eller læsion af kvindeligt kønsorgan" "DT812H - Utilsigtet peroperativ punktur eller læsion af kvindeligt kønsorgan"
* #DT812UC "Utilsigtet peroperativ punktur eller læsion af urinleder" "DT812UC - Utilsigtet peroperativ punktur eller læsion af urinleder"
* #DT812UD "Utilsigtet peroperativ punktur eller læsion af urinblære" "DT812UD - Utilsigtet peroperativ punktur eller læsion af urinblære"
* #DT812UE "Utilsigtet peroperativ punktur eller læsion af urinrør" "DT812UE - Utilsigtet peroperativ punktur eller læsion af urinrør"
* #DT814F "Postoperativ sårinfektion" "DT814F - Postoperativ sårinfektion"
* #DT814U "Postoperativ urinvejsinfektion" "DT814U - Postoperativ urinvejsinfektion"
* #DT818F "Peroperativ blødning UNS" "DT818F - Peroperativ blødning UNS"
* #DT835 "Infektion eller inflammation omkring protese, implantat eller transplantat i urinvejene" "DT835 - Infektion eller inflammation omkring protese, implantat eller transplantat i urinvejene"
* #DT836 "Infektion eller inflammation omkring protese, implantat eller transplantat i kønsorganerne" "DT836 - Infektion eller inflammation omkring protese, implantat eller transplantat i kønsorganerne"
* #DT983C "Postoperativ seksuel dysfunktion" "DT983C - Postoperativ seksuel dysfunktion"
* #KJHC10 "Rekonstruktion af sphincter ani" "KJHC10 - Rekonstruktion af sphincter ani"
* #KKBF00 "Fjernelse af fremmedlegeme i urinleder" "KKBF00 - Fjernelse af fremmedlegeme i urinleder"
* #KKCF01 "Perkutan endoskopisk fjernelse af fremmedlegeme i urinblære" "KKCF01 - Perkutan endoskopisk fjernelse af fremmedlegeme i urinblære"
* #KKDE20 "Fjernelse af fremmedlegeme fra urinrør" "KKDE20 - Fjernelse af fremmedlegeme fra urinrør"
* #KKDG00 "Retropubisk supension af urinrør" "KKDG00 - Retropubisk supension af urinrør"
* #KKDG30 "Abdominal uretrocystopeksi med slynge" "KKDG30 - Abdominal uretrocystopeksi med slynge"
* #KKDV22 "Uretroskopisk submukøs injektionsbehandling i urinrør" "KKDV22 - Uretroskopisk submukøs injektionsbehandling i urinrør"
* #KLCD10 "Vaginal hysterektomi" "KLCD10 - Vaginal hysterektomi"
* #KLCG20 "Hysteropeksi" "KLCG20 - Hysteropeksi"
* #KLCG21 "Laparoskopisk hysteropeksi" "KLCG21 - Laparoskopisk hysteropeksi"
* #KLCG21A "Laparoskopisk hysteropeksi med mesh" "KLCG21A - Laparoskopisk hysteropeksi med mesh"
* #KLDC10 "Resektion af livmoderhals" "KLDC10 - Resektion af livmoderhals"
* #KLED00 "Kolpektomi" "KLED00 - Kolpektomi"
* #KLEE00 "Sutur af vagina" "KLEE00 - Sutur af vagina"
* #KLEF00 "Forreste kolporafi" "KLEF00 - Forreste kolporafi"
* #KLEF00A "Forreste kolporafi med meche" "KLEF00A - Forreste kolporafi med meche"
* #KLEF03 "Bageste kolporafi" "KLEF03 - Bageste kolporafi"
* #KLEF03A "Bageste kolporafi med meche" "KLEF03A - Bageste kolporafi med meche"
* #KLEF20 "Partiel kolpokleise" "KLEF20 - Partiel kolpokleise"
* #KLEF40 "Vaginal operation for enterocele" "KLEF40 - Vaginal operation for enterocele"
* #KLEF40A "Vaginal operation for enterocele med meche" "KLEF40A - Vaginal operation for enterocele med meche"
* #KLEF43 "Abdominal operation for enterocele" "KLEF43 - Abdominal operation for enterocele"
* #KLEF43A "Abdominal operation for enterocele med meche" "KLEF43A - Abdominal operation for enterocele med meche"
* #KLEF50 "Abdominal apikal kolpopeksi efter tidligere hysterektomi" "KLEF50 - Abdominal apikal kolpopeksi efter tidligere hysterektomi"
* #KLEF50A "Abdominal apikal kolpopeksi eft. tidl. hysterektomi m. meche" "KLEF50A - Abdominal apikal kolpopeksi eft. tidl. hysterektomi m. meche"
* #KLEF51 "Laparoskopisk apikal kolpopeksi efter tidligere hysterektomi" "KLEF51 - Laparoskopisk apikal kolpopeksi efter tidligere hysterektomi"
* #KLEF51A "Laparoskop. apikal kolpopeksi eft.tidl. hysterektomi m. meche" "KLEF51A - Laparoskop. apikal kolpopeksi eft.tidl. hysterektomi m. meche"
* #KLEF53 "Vaginal apikal kolpopeksi efter tidligere hysterektomi" "KLEF53 - Vaginal apikal kolpopeksi efter tidligere hysterektomi"
* #KLEF53A "Vaginal apikal kolpopeksi efter tidl. hysterektomi med meche" "KLEF53A - Vaginal apikal kolpopeksi efter tidl. hysterektomi med meche"
* #KLEF53B "Vaginal apikal kolpopeksi til det sakrospinøse ligament" "KLEF53B - Vaginal apikal kolpopeksi til det sakrospinøse ligament"
* #KLEF60 "Vaginal lateral kolpopeksi" "KLEF60 - Vaginal lateral kolpopeksi"
* #KLEF63 "Abdominal lateral kolpopeksi" "KLEF63 - Abdominal lateral kolpopeksi"
* #KLEG10 "Vaginal uretrocystopeksi med slynge" "KLEG10 - Vaginal uretrocystopeksi med slynge"
* #KLEG10A "Vaginal uretrocystopeksi med slynge gennem foramen obturatum" "KLEG10A - Vaginal uretrocystopeksi med slynge gennem foramen obturatum"
* #KLFE00 "Sutur af vulva" "KLFE00 - Sutur af vulva"
* #KLFE96 "Anden rekonstruktion på vulva eller perineum" "KLFE96 - Anden rekonstruktion på vulva eller perineum"
* #KLWB00 "Reoperation ved overfladisk infektion efter gynækologisk operation" "KLWB00 - Reoperation ved overfladisk infektion efter gynækologisk operation"
* #KLWC00 "Reoperation ved dyb infektion efter gynækologisk operation" "KLWC00 - Reoperation ved dyb infektion efter gynækologisk operation"
* #KLWC01 "Laparoskopisk reoperation ved dyb infektion efter gynækologisk operation" "KLWC01 - Laparoskopisk reoperation ved dyb infektion efter gynækologisk operation"
* #KLWD00 "Reoperation for overfladisk blødning efter gynækologisk operation" "KLWD00 - Reoperation for overfladisk blødning efter gynækologisk operation"
* #KLWE00 "Reoperation for dyb blødning efter gynækologisk operation" "KLWE00 - Reoperation for dyb blødning efter gynækologisk operation"
* #KLWE01 "Laparoskopisk reoperation for dyb blødning efter gynækologisk operation" "KLWE01 - Laparoskopisk reoperation for dyb blødning efter gynækologisk operation"
* #KLWW96 "Anden reoperation efter gynækologisk operation" "KLWW96 - Anden reoperation efter gynækologisk operation"
* #KLWW96A "Fjernelse af fremmedlegeme i bækkenhulen efter gynækologisk operation" "KLWW96A - Fjernelse af fremmedlegeme i bækkenhulen efter gynækologisk operation"
* #KLWW97A "Laparoskopisk fjernelse af fremmedlegeme i bækkenhulen efter gynækologisk operation" "KLWW97A - Laparoskopisk fjernelse af fremmedlegeme i bækkenhulen efter gynækologisk operation"
* #KTLE10 "Fjernelse af fremmedlegeme fra vagina" "KTLE10 - Fjernelse af fremmedlegeme fra vagina"
* #KTLW99A "Løsning eller overskæring af vaginal slynge" "KTLW99A - Løsning eller overskæring af vaginal slynge"
* #KTLW99B "Stramning af vaginal slynge" "KTLW99B - Stramning af vaginal slynge"
* #KUKC02 "Cystoskopi" "KUKC02 - Cystoskopi"
* #KZLA01 "Suspension af vaginaltop a.m. McCall" "KZLA01 - Suspension af vaginaltop a.m. McCall"
* #KZLA02 "Suspension af vaginaltop a.m. Bob Shull" "KZLA02 - Suspension af vaginaltop a.m. Bob Shull"
* #KZXF84A "Ikke resorberbar sutur" "KZXF84A - Ikke resorberbar sutur"
* #KZXF84B "Korttidsresorberbar sutur (< 3 uger)" "KZXF84B - Korttidsresorberbar sutur (< 3 uger)"
* #KZXF84C "Forsinket resorberbar sutur" "KZXF84C - Forsinket resorberbar sutur"
* #KZXX00 "Anvendelse af robot" "KZXX00 - Anvendelse af robot"
* #ZZ1295 "Væske og vandladningsskema" "ZZ1295 - Væske og vandladningsskema"

// Merged from DiseasesUnspecified (Diseases Unspecified) — 2 codes
* #DD472 "Monoklonal gammopati med ubestemt signifikans (MGUS)" "DD472 - Monoklonal gammopati med ubestemt signifikans (MGUS)"
* #ZM973A3 "Osteosklerotisk myelom (POEMS syndrom)" "ZM973A3 - Osteosklerotisk myelom (POEMS syndrom)"
