CodeSystem: PRDcodes
Title: "ERA PRD Codes"
Description: "European Renal Association (ERA)  Primary Renal Disease (PRD)"

* ^status = #active
* ^publisher = "RKKP"
* ^date = "2024-01-10T00:00:00+02:00"
* ^contact[0].telecom[0].system = #url
* ^contact[0].telecom[0].value = "https://www.rkkp.dk/"
* ^content = #complete
* ^caseSensitive = false

* #prd1003 "Adult nephrotic syndrome - no histology (1003)" "Adult nephrotic syndrome - no histology"
* #prd1019 "Nephrotic syndrome of childhood - steroid sensitive - no histology (1019)" "Nephrotic syndrome of childhood - steroid sensitive - no histology"
* #prd1026 "Congenital nephrotic syndrome (CNS) - no histology (1026)" "Congenital nephrotic syndrome (CNS) - no histology"
* #prd1035 "Congenital nephrotic syndrome (CNS) - Finnish type - no histology (1035)" "Congenital nephrotic syndrome (CNS) - Finnish type - no histology"
* #prd1042 "Congenital nephrotic syndrome (CNS) - Finnish type - histologically proven (1042)" "Congenital nephrotic syndrome (CNS) - Finnish type - histologically proven"
* #prd1057 "Congenital nephrotic syndrome (CNS) - diffuse mesangial sclerosis (1057)" "Congenital nephrotic syndrome (CNS) - diffuse mesangial sclerosis"
* #prd1061 "Congenital nephrotic syndrome (CNS) - focal segmental glomerulosclerosis (FSGS) (1061)" "Congenital nephrotic syndrome (CNS) - focal segmental glomerulosclerosis (FSGS)"
* #prd1074 "Denys-Drash syndrome (1074)" "Denys-Drash syndrome"
* #prd1088 "Congenital nephrotic syndrome (CNS) - congenital infection (1088)" "Congenital nephrotic syndrome (CNS) - congenital infection"
* #prd1090 "Minimal change nephropathy - no histology (1090)" "Minimal change nephropathy - no histology"
* #prd1100 "Minimal change nephropathy - histologically proven (1100)" "Minimal change nephropathy - histologically proven"
* #prd1116 "IgA nephropathy - no histology (1116)" "IgA nephropathy - no histology"
* #prd1128 "IgA nephropathy - histologically proven (1128)" "IgA nephropathy - histologically proven"
* #prd1137 "Familial IgA nephropathy - no histology (1137)" "Familial IgA nephropathy - no histology"
* #prd1144 "Familial IgA nephropathy - histologically proven (1144)" "Familial IgA nephropathy - histologically proven"
* #prd1159 "IgA nephropathy secondary to liver cirrhosis - no histology (1159)" "IgA nephropathy secondary to liver cirrhosis - no histology"
* #prd1163 "IgA nephropathy secondary to liver cirrhosis - histologically proven (1163)" "IgA nephropathy secondary to liver cirrhosis - histologically proven"
* #prd1171 "IgM - associated nephropathy (1171)" "IgM - associated nephropathy"
* #prd1185 "Membranous nephropathy - idiopathic (1185)" "Membranous nephropathy - idiopathic"
* #prd1192 "Membranous nephropathy - malignancy associated (1192)" "Membranous nephropathy - malignancy associated"
* #prd1205 "Membranous nephropathy - drug induced (1205)" "Membranous nephropathy - drug induced"
* #prd1214 "Membranous nephropathy - infection associated (1214)" "Membranous nephropathy - infection associated"
* #prd1222 "Mesangiocapillary glomerulonephritis type 1 (1222)" "Mesangiocapillary glomerulonephritis type 1"
* #prd1233 "Mesangiocapillary glomerulonephritis type 2 (dense deposit disease) (1233)" "Mesangiocapillary glomerulonephritis type 2 (dense deposit disease)"
* #prd1246 "Mesangiocapillary glomerulonephritis type 3 (1246)" "Mesangiocapillary glomerulonephritis type 3"
* #prd1251 "Idiopathic rapidly progressive (crescentic) glomerulonephritis (1251)" "Idiopathic rapidly progressive (crescentic) glomerulonephritis"
* #prd1267 "Primary focal segmental glomerulosclerosis (FSGS) (1267)" "Primary focal segmental glomerulosclerosis (FSGS)"
* #prd1279 "Familial focal segmental glomerulosclerosis (FSGS) - autosomal recessive - no histology (1279)" "Familial focal segmental glomerulosclerosis (FSGS) - autosomal recessive - no histology"
* #prd1280 "Familial focal segmental glomerulosclerosis (FSGS) - autosomal recessive - histologically proven (1280)" "Familial focal segmental glomerulosclerosis (FSGS) - autosomal recessive - histologically proven"
* #prd1298 "Familial focal segmental glomerulosclerosis (FSGS) - autosomal dominant - no histology (1298)" "Familial focal segmental glomerulosclerosis (FSGS) - autosomal dominant - no histology"
* #prd1308 "Familial focal segmental glomerulosclerosis (FSGS) - autosomal dominant - histologically proven (1308)" "Familial focal segmental glomerulosclerosis (FSGS) - autosomal dominant - histologically proven"
* #prd1312 "Focal segmental glomerulosclerosis (FSGS) secondary to obesity - no histology (1312)" "Focal segmental glomerulosclerosis (FSGS) secondary to obesity - no histology"
* #prd1320 "Focal segmental glomerulosclerosis (FSGS) secondary to obesity - histologically proven (1320)" "Focal segmental glomerulosclerosis (FSGS) secondary to obesity - histologically proven"
* #prd1331 "Diffuse endocapillary glomerulonephritis (1331)" "Diffuse endocapillary glomerulonephritis"
* #prd1349 "Mesangial proliferative glomerulonephritis  (1349)" "Mesangial proliferative glomerulonephritis"
* #prd1354 "Focal and segmental proliferative glomerulonephritis (1354)" "Focal and segmental proliferative glomerulonephritis"
* #prd1365 "Glomerulonephritis - secondary to systemic disease  (1365)" "Glomerulonephritis - secondary to systemic disease"
* #prd1377 "Glomerulonephritis - histologically indeterminate (1377)" "Glomerulonephritis - histologically indeterminate"
* #prd1383 "Systemic vasculitis - ANCA negative - histologically proven (1383)" "Systemic vasculitis - ANCA negative - histologically proven"
* #prd1396 "Systemic vasculitis - ANCA positive - no histology (1396)" "Systemic vasculitis - ANCA positive - no histology"
* #prd1401 "Granulomatosis with polyangiitis - no histology (1401)" "Granulomatosis with polyangiitis - no histology"
* #prd1417 "Granulomatosis with polyangiitis - histologically proven (1417)" "Granulomatosis with polyangiitis - histologically proven"
* #prd1429 "Microscopic polyangiitis - histologically proven (1429)" "Microscopic polyangiitis - histologically proven"
* #prd1438 "Churg-Strauss syndrome - no histology (1438)" "Churg-Strauss syndrome - no histology"
* #prd1440 "Churg-Strauss syndrome - histologically proven (1440)" "Churg-Strauss syndrome - histologically proven"
* #prd1455 "Polyarteritis nodosa (1455)" "Polyarteritis nodosa"
* #prd1464 "Anti-Glomerular basement membrane (GBM) disease / Goodpasture's syndrome - no histology (1464)" "Anti-Glomerular basement membrane (GBM) disease / Goodpasture's syndrome - no histology"
* #prd1472 "Anti-Glomerular basement membrane (GBM) disease / Goodpasture's syndrome - histologically proven (1472)" "Anti-Glomerular basement membrane (GBM) disease / Goodpasture's syndrome - histologically proven"
* #prd1486 "Systemic lupus erythematosus / nephritis - no histology (1486)" "Systemic lupus erythematosus / nephritis - no histology"
* #prd1493 "Systemic lupus erythematosus / nephritis - histologically proven (1493)" "Systemic lupus erythematosus / nephritis - histologically proven"
* #prd1504 "Henoch-Schönlein purpura / nephritis - no histology (1504)" "Henoch-Schönlein purpura / nephritis - no histology"
* #prd1515 "Henoch-Schönlein purpura / nephritis - histologically proven (1515)" "Henoch-Schönlein purpura / nephritis - histologically proven"
* #prd1527 "Renal scleroderma / systemic sclerosis - no histology (1527)" "Renal scleroderma / systemic sclerosis - no histology"
* #prd1536 "Renal scleroderma / systemic sclerosis - histologically proven (1536)" "Renal scleroderma / systemic sclerosis - histologically proven"
* #prd1543 "Essential mixed cryoglobulinaemia - no histology (1543)" "Essential mixed cryoglobulinaemia - no histology"
* #prd1558 "Essential mixed cryoglobulinaemia - histologically proven (1558)" "Essential mixed cryoglobulinaemia - histologically proven"
* #prd1562 "Cryoglobulinaemia secondary to hepatitis C - no histology (1562)" "Cryoglobulinaemia secondary to hepatitis C - no histology"
* #prd1570 "Cryoglobulinaemia secondary to hepatitis C - histologically proven (1570)" "Cryoglobulinaemia secondary to hepatitis C - histologically proven"
* #prd1589 "Cryoglobulinaemia secondary to systemic disease - no histology (1589)" "Cryoglobulinaemia secondary to systemic disease - no histology"
* #prd1591 "Cryoglobulinaemia secondary to systemic disease - histologically proven (1591)" "Cryoglobulinaemia secondary to systemic disease - histologically proven"
* #prd1602 "Primary reflux nephropathy - sporadic (1602)" "Primary reflux nephropathy - sporadic"
* #prd1618 "Familial reflux nephropathy (1618)" "Familial reflux nephropathy"
* #prd1625 "Congenital dysplasia / hypoplasia (1625)" "Congenital dysplasia / hypoplasia"
* #prd1639 "Multicystic dysplastic kidneys (1639)" "Multicystic dysplastic kidneys"
* #prd1641 "Renal dysplasia due to fetal ACE-inhibitor exposure (1641)" "Renal dysplasia due to fetal ACE-inhibitor exposure"
* #prd1656 "Glomerulocystic disease (1656)" "Glomerulocystic disease"
* #prd1660 "Congenital pelvi-ureteric junction obstruction (1660)" "Congenital pelvi-ureteric junction obstruction"
* #prd1673 "Congenital vesico-ureteric junction obstruction (1673)" "Congenital vesico-ureteric junction obstruction"
* #prd1687 "Posterior urethral valves (1687)" "Posterior urethral valves"
* #prd1694 "Syndrome of agenesis of abdominal muscles - prune belly syndrome (1694)" "Syndrome of agenesis of abdominal muscles - prune belly syndrome"
* #prd1706 "Congenital neurogenic bladder (1706)" "Congenital neurogenic bladder"
* #prd1710 "Bladder exstrophy (1710)" "Bladder exstrophy"
* #prd1723 "Megacystis-megaureter (1723)" "Megacystis-megaureter"
* #prd1734 "Oligomeganephronia (1734)" "Oligomeganephronia"
* #prd1747 "Renal papillary necrosis (1747)" "Renal papillary necrosis"
* #prd1752 "Acquired obstructive uropathy / nephropathy (1752)" "Acquired obstructive uropathy / nephropathy"
* #prd1768 "Acquired obstructive nephropathy due to neurogenic bladder (1768)" "Acquired obstructive nephropathy due to neurogenic bladder"
* #prd1775 "Obstructive nephropathy due to prostatic hypertrophy (1775)" "Obstructive nephropathy due to prostatic hypertrophy"
* #prd1781 "Obstructive nephropathy due to prostate cancer (1781)" "Obstructive nephropathy due to prostate cancer"
* #prd1799 "Obstructive nephropathy due to bladder cancer (1799)" "Obstructive nephropathy due to bladder cancer"
* #prd1809 "Obstructive nephropathy due to other malignancies (1809)" "Obstructive nephropathy due to other malignancies"
* #prd1813 "Idiopathic retroperitoneal fibrosis (1813)" "Idiopathic retroperitoneal fibrosis"
* #prd1821 "Retroperitoneal fibrosis secondary to malignancies (1821)" "Retroperitoneal fibrosis secondary to malignancies"
* #prd1832 "Calculus nephropathy / urolithiasis (1832)" "Calculus nephropathy / urolithiasis"
* #prd1845 "Calcium oxalate urolithiasis (1845)" "Calcium oxalate urolithiasis"
* #prd1850 "Enteric hyperoxaluria  (1850)" "Enteric hyperoxaluria"
* #prd1866 "Magnesium ammonium phosphate (struvite) urolithiasis (1866)" "Magnesium ammonium phosphate (struvite) urolithiasis"
* #prd1878 "Uric acid urolithiasis (1878)" "Uric acid urolithiasis"
* #prd1884 "Tubulointerstitial nephritis - no histology (1884)" "Tubulointerstitial nephritis - no histology"
* #prd1897 "Tubulointerstitial nephritis - histologically proven (1897)" "Tubulointerstitial nephritis - histologically proven"
* #prd1907 "Familial interstitial nephropathy - no histology (1907)" "Familial interstitial nephropathy - no histology"
* #prd1911 "Familial interstitial nephropathy - histologically proven (1911)" "Familial interstitial nephropathy - histologically proven"
* #prd1924 "Tubulointerstitial nephritis associated with autoimmune disease - no histology (1924)" "Tubulointerstitial nephritis associated with autoimmune disease - no histology"
* #prd1930 "Tubulointerstitial nephritis associated with autoimmune disease - histologically proven (1930)" "Tubulointerstitial nephritis associated with autoimmune disease - histologically proven"
* #prd1948 "Tubulointerstitial nephritis with uveitis (TINU) - no histology (1948)" "Tubulointerstitial nephritis with uveitis (TINU) - no histology"
* #prd1953 "Tubulointerstitial nephritis with uveitis (TINU) - histologically proven (1953)" "Tubulointerstitial nephritis with uveitis (TINU) - histologically proven"
* #prd1969 "Renal sarcoidosis - no histology (1969)" "Renal sarcoidosis - no histology"
* #prd1976 "Renal sarcoidosis - histologically proven (1976)" "Renal sarcoidosis - histologically proven"
* #prd1982 "Aristolochic acid nephropathy (Balkan / Chinese herb / endemic nephropathy) - no histology (1982)" "Aristolochic acid nephropathy (Balkan / Chinese herb / endemic nephropathy) - no histology"
* #prd1995 "Aristolochic acid nephropathy (Balkan / Chinese herb / endemic nephropathy) - histologically proven (1995)" "Aristolochic acid nephropathy (Balkan / Chinese herb / endemic nephropathy) - histologically proven"
* #prd2005 "Drug-induced tubulointerstitial nephritis  - no histology (2005)" "Drug-induced tubulointerstitial nephritis  - no histology"
* #prd2014 "Drug-induced tubulointerstitial nephritis - histologically proven (2014)" "Drug-induced tubulointerstitial nephritis - histologically proven"
* #prd2022 "Nephropathy due to analgesic drugs - no histology (2022)" "Nephropathy due to analgesic drugs - no histology"
* #prd2033 "Nephropathy due to analgesic drugs - histologically proven (2033)" "Nephropathy due to analgesic drugs - histologically proven"
* #prd2046 "Nephropathy due to ciclosporin - no histology (2046)" "Nephropathy due to ciclosporin - no histology"
* #prd2051 "Nephropathy due to ciclosporin - histologically proven (2051)" "Nephropathy due to ciclosporin - histologically proven"
* #prd2067 "Nephropathy due to tacrolimus - no histology (2067)" "Nephropathy due to tacrolimus - no histology"
* #prd2079 "Nephropathy due to tacrolimus - histologically proven (2079)" "Nephropathy due to tacrolimus - histologically proven"
* #prd2080 "Nephropathy due to aminoglycosides - no histology (2080)" "Nephropathy due to aminoglycosides - no histology"
* #prd2098 "Nephropathy due to aminoglycosides - histologically proven (2098)" "Nephropathy due to aminoglycosides - histologically proven"
* #prd2108 "Nephropathy due to amphotericin - no histology (2108)" "Nephropathy due to amphotericin - no histology"
* #prd2112 "Nephropathy due to amphotericin - histologically proven (2112)" "Nephropathy due to amphotericin - histologically proven"
* #prd2120 "Nephropathy due to cisplatin - no histology (2120)" "Nephropathy due to cisplatin - no histology"
* #prd2131 "Nephropathy due to cisplatin - histologically proven (2131)" "Nephropathy due to cisplatin - histologically proven"
* #prd2149 "Nephropathy due to lithium - no histology (2149)" "Nephropathy due to lithium - no histology"
* #prd2154 "Nephropathy due to lithium - histologically proven (2154)" "Nephropathy due to lithium - histologically proven"
* #prd2165 "Lead induced nephropathy - no histology (2165)" "Lead induced nephropathy - no histology"
* #prd2177 "Lead induced nephropathy - histologically proven (2177)" "Lead induced nephropathy - histologically proven"
* #prd2183 "Acute urate nephropathy - no histology (2183)" "Acute urate nephropathy - no histology"
* #prd2196 "Acute urate nephropathy - histologically proven (2196)" "Acute urate nephropathy - histologically proven"
* #prd2203 "Chronic urate nephropathy - histologically proven (2203)" "Chronic urate nephropathy - histologically proven"
* #prd2219 "Radiation nephritis (2219)" "Radiation nephritis"
* #prd2226 "Renal / perinephric abscess (2226)" "Renal / perinephric abscess"
* #prd2235 "Renal tuberculosis (2235)" "Renal tuberculosis"
* #prd2242 "Leptospirosis (2242)" "Leptospirosis"
* #prd2257 "Hantavirus nephropathy (2257)" "Hantavirus nephropathy"
* #prd2261 "Xanthogranulomatous pyelonephritis (2261)" "Xanthogranulomatous pyelonephritis"
* #prd2274 "Nephropathy related to HIV - no histology (2274)" "Nephropathy related to HIV - no histology"
* #prd2288 "Nephropathy related to HIV - histologically proven (2288)" "Nephropathy related to HIV - histologically proven"
* #prd2290 "Schistosomiasis (2290)" "Schistosomiasis"
* #prd2300 "Other specific infection (2300)" "Other specific infection"
* #prd2316 "Diabetic nephropathy in type I diabetes - no histology (2316)" "Diabetic nephropathy in type I diabetes - no histology"
* #prd2328 "Diabetic nephropathy in type I diabetes - histologically proven (2328)" "Diabetic nephropathy in type I diabetes - histologically proven"
* #prd2337 "Diabetic nephropathy in type II diabetes - no histology (2337)" "Diabetic nephropathy in type II diabetes - no histology"
* #prd2344 "Diabetic nephropathy in type II diabetes - histologically proven (2344)" "Diabetic nephropathy in type II diabetes - histologically proven"
* #prd2359 "Chronic hypertensive nephropathy - no histology (2359)" "Chronic hypertensive nephropathy - no histology"
* #prd2363 "Chronic hypertensive nephropathy - histologically proven (2363)" "Chronic hypertensive nephropathy - histologically proven"
* #prd2371 "Malignant hypertensive nephropathy / accelerated hypertensive nephropathy - no histology (2371)" "Malignant hypertensive nephropathy / accelerated hypertensive nephropathy - no histology"
* #prd2385 "Malignant hypertensive nephropathy / accelerated hypertensive nephropathy - histologically proven (2385)" "Malignant hypertensive nephropathy / accelerated hypertensive nephropathy - histologically proven"
* #prd2392 "Ageing kidney - no histology (2392)" "Ageing kidney - no histology"
* #prd2407 "Ischaemic nephropathy - no histology (2407)" "Ischaemic nephropathy - no histology"
* #prd2411 "Ischaemic nephropathy / microvascular disease - histologically proven (2411)" "Ischaemic nephropathy / microvascular disease - histologically proven"
* #prd2424 "Renal artery stenosis (2424)" "Renal artery stenosis"
* #prd2430 "Atheroembolic renal disease - no histology (2430)" "Atheroembolic renal disease - no histology"
* #prd2448 "Atheroembolic renal disease - histologically proven (2448)" "Atheroembolic renal disease - histologically proven"
* #prd2453 "Fibromuscular dysplasia of renal artery (2453)" "Fibromuscular dysplasia of renal artery"
* #prd2469 "Renal arterial thrombosis / occlusion (2469)" "Renal arterial thrombosis / occlusion"
* #prd2476 "Renal vein thrombosis (2476)" "Renal vein thrombosis"
* #prd2482 "Cardiorenal syndrome (2482)" "Cardiorenal syndrome"
* #prd2495 "Hepatorenal syndrome (2495)" "Hepatorenal syndrome"
* #prd2509 "Renal amyloidosis (2509)" "Renal amyloidosis"
* #prd2513 "AA amyloid secondary to chronic inflammation (2513)" "AA amyloid secondary to chronic inflammation"
* #prd2521 "AL amyloid secondary to plasma cell dyscrasia (2521)" "AL amyloid secondary to plasma cell dyscrasia"
* #prd2532 "Familial amyloid secondary to protein mutations - no histology (2532)" "Familial amyloid secondary to protein mutations - no histology"
* #prd2545 "Familial amyloid secondary to protein mutations - histologically proven (2545)" "Familial amyloid secondary to protein mutations - histologically proven"
* #prd2550 "Familial AA amyloid secondary to familial Mediterranean fever / TRAPS (Hibernian fever) - no histology (2550)" "Familial AA amyloid secondary to familial Mediterranean fever / TRAPS (Hibernian fever) - no histology"
* #prd2566 "Familial AA amyloid secondary to familial Mediterranean fever / TRAPS (Hibernian fever) - histologically proven (2566)" "Familial AA amyloid secondary to familial Mediterranean fever / TRAPS (Hibernian fever) - histologically proven"
* #prd2578 "Myeloma kidney - no histology (2578)" "Myeloma kidney - no histology"
* #prd2584 "Myeloma cast nephropathy - histologically proven (2584)" "Myeloma cast nephropathy - histologically proven"
* #prd2597 "Light chain deposition disease (2597)" "Light chain deposition disease"
* #prd2606 "Immunotactoid / fibrillary nephropathy (2606)" "Immunotactoid / fibrillary nephropathy"
* #prd2610 "Haemolytic uraemic syndrome (HUS) - diarrhoea associated (2610)" "Haemolytic uraemic syndrome (HUS) - diarrhoea associated"
* #prd2623 "Atypical haemolytic uraemic syndrome (HUS) - diarrhoea negative (2623)" "Atypical haemolytic uraemic syndrome (HUS) - diarrhoea negative"
* #prd2634 "Thrombotic thrombocytopenic purpura (TTP) (2634)" "Thrombotic thrombocytopenic purpura (TTP)"
* #prd2647 "Haemolytic uraemic syndrome (HUS) secondary to systemic disease (2647)" "Haemolytic uraemic syndrome (HUS) secondary to systemic disease"
* #prd2652 "Congenital haemolytic uraemic syndrome (HUS)  (2652)" "Congenital haemolytic uraemic syndrome (HUS)"
* #prd2668 "Familial haemolytic uraemic syndrome (HUS) (2668)" "Familial haemolytic uraemic syndrome (HUS)"
* #prd2675 "Familial thrombotic thrombocytopenic purpura (TTP) (2675)" "Familial thrombotic thrombocytopenic purpura (TTP)"
* #prd2681 "Nephropathy due to eclampsia (2681)" "Nephropathy due to eclampsia"
* #prd2699 "Sickle cell nephropathy - no histology (2699)" "Sickle cell nephropathy - no histology"
* #prd2702 "Sickle cell nephropathy - histologically proven (2702)" "Sickle cell nephropathy - histologically proven"
* #prd2718 "Autosomal dominant (AD) polycystic kidney disease (2718)" "Autosomal dominant (AD) polycystic kidney disease"
* #prd2725 "Autosomal dominant (AD) polycystic kidney disease type I (2725)" "Autosomal dominant (AD) polycystic kidney disease type I"
* #prd2739 "Autosomal dominant (AD) polycystic kidney disease type II (2739)" "Autosomal dominant (AD) polycystic kidney disease type II"
* #prd2741 "Autosomal recessive (AR) polycystic kidney disease (2741)" "Autosomal recessive (AR) polycystic kidney disease"
* #prd2756 "Alport syndrome - no histology (2756)" "Alport syndrome - no histology"
* #prd2760 "Alport syndrome - histologically proven (2760)" "Alport syndrome - histologically proven"
* #prd2773 "Benign familial haematuria (2773)" "Benign familial haematuria"
* #prd2787 "Thin basement membrane disease (2787)" "Thin basement membrane disease"
* #prd2794 "Cystic kidney disease (2794)" "Cystic kidney disease"
* #prd2804 "Medullary cystic kidney disease type I (2804)" "Medullary cystic kidney disease type I"
* #prd2815 "Medullary cystic kidney disease type II (2815)" "Medullary cystic kidney disease type II"
* #prd2827 "Uromodulin-associated nephropathy (familial juvenile hyperuricaemic nephropathy) (2827)" "Uromodulin-associated nephropathy (familial juvenile hyperuricaemic nephropathy)"
* #prd2836 "Nephronophthisis (2836)" "Nephronophthisis"
* #prd2843 "Nephronophthisis - type 1 (juvenile type) (2843)" "Nephronophthisis - type 1 (juvenile type)"
* #prd2858 "Nephronophthisis - type 2 (infantile type) (2858)" "Nephronophthisis - type 2 (infantile type)"
* #prd2862 "Nephronophthisis - type 3 (adolescent type) (2862)" "Nephronophthisis - type 3 (adolescent type)"
* #prd2870 "Nephronophthisis - type 4 (juvenile type) (2870)" "Nephronophthisis - type 4 (juvenile type)"
* #prd2889 "Nephronophthisis - type 5 (2889)" "Nephronophthisis - type 5"
* #prd2891 "Nephronophthisis - type 6 (2891)" "Nephronophthisis - type 6"
* #prd2901 "Primary Fanconi syndrome (2901)" "Primary Fanconi syndrome"
* #prd2917 "Tubular disorder as part of inherited metabolic diseases (2917)" "Tubular disorder as part of inherited metabolic diseases"
* #prd2929 "Dent disease (2929)" "Dent disease"
* #prd2938 "Lowe syndrome (oculocerebrorenal syndrome) (2938)" "Lowe syndrome (oculocerebrorenal syndrome)"
* #prd2940 "Inherited aminoaciduria (2940)" "Inherited aminoaciduria"
* #prd2955 "Cystinuria (2955)" "Cystinuria"
* #prd2964 "Cystinosis (2964)" "Cystinosis"
* #prd2972 "Inherited renal glycosuria (2972)" "Inherited renal glycosuria"
* #prd2986 "Hypophosphataemic rickets X-linked (XL) (2986)" "Hypophosphataemic rickets X-linked (XL)"
* #prd2993 "Hypophosphataemic rickets autosomal recessive (AR) (2993)" "Hypophosphataemic rickets autosomal recessive (AR)"
* #prd3000 "Primary renal tubular acidosis (RTA) (3000)" "Primary renal tubular acidosis (RTA)"
* #prd3016 "Proximal renal tubular acidosis (RTA) - type II (3016)" "Proximal renal tubular acidosis (RTA) - type II"
* #prd3028 "Distal renal tubular acidosis (RTA) - type I (3028)" "Distal renal tubular acidosis (RTA) - type I"
* #prd3037 "Distal renal tubular acidosis with sensorineural deafness - gene mutations (3037)" "Distal renal tubular acidosis with sensorineural deafness - gene mutations"
* #prd3044 "Nephrogenic diabetes insipidus (3044)" "Nephrogenic diabetes insipidus"
* #prd3059 "Lesch Nyhan syndrome - hypoxanthine guanine phosphoribosyl transferase deficiency  (3059)" "Lesch Nyhan syndrome - hypoxanthine guanine phosphoribosyl transferase deficiency"
* #prd3063 "Phosphoribosyl pyrophosphate synthetase (PRPPS) superactivity (3063)" "Phosphoribosyl pyrophosphate synthetase (PRPPS) superactivity"
* #prd3071 "Alagille syndrome (3071)" "Alagille syndrome"
* #prd3085 "Bartter syndrome (3085)" "Bartter syndrome"
* #prd3092 "Gitelman syndrome (3092)" "Gitelman syndrome"
* #prd3102 "Liddle syndrome (3102)" "Liddle syndrome"
* #prd3118 "Apparent mineralocorticoid excess (3118)" "Apparent mineralocorticoid excess"
* #prd3125 "Glucocorticoid suppressible hyperaldosteronism (3125)" "Glucocorticoid suppressible hyperaldosteronism"
* #prd3139 "Inherited / genetic diabetes mellitus type II (3139)" "Inherited / genetic diabetes mellitus type II"
* #prd3141 "Pseudohypoaldosteronism type 1 (3141)" "Pseudohypoaldosteronism type 1"
* #prd3156 "Pseudohypoaldosteronism type 2 (Gordon syndrome) (3156)" "Pseudohypoaldosteronism type 2 (Gordon syndrome)"
* #prd3160 "Familial hypocalciuric hypercalcaemia (3160)" "Familial hypocalciuric hypercalcaemia"
* #prd3173 "Familial hypercalciuric hypocalcaemia (3173)" "Familial hypercalciuric hypocalcaemia"
* #prd3187 "Familial hypomagnesaemia (3187)" "Familial hypomagnesaemia"
* #prd3194 "Primary hyperoxaluria (3194)" "Primary hyperoxaluria"
* #prd3207 "Primary hyperoxaluria type I (3207)" "Primary hyperoxaluria type I"
* #prd3211 "Primary hyperoxaluria type II (3211)" "Primary hyperoxaluria type II"
* #prd3224 "Fabry disease - no histology (3224)" "Fabry disease - no histology"
* #prd3230 "Fabry disease - histologically proven (3230)" "Fabry disease - histologically proven"
* #prd3248 "Xanthinuria (3248)" "Xanthinuria"
* #prd3253 "Nail-patella syndrome (3253)" "Nail-patella syndrome"
* #prd3269 "Rubinstein-Taybi syndrome (3269)" "Rubinstein-Taybi syndrome"
* #prd3276 "Tuberous sclerosis (3276)" "Tuberous sclerosis"
* #prd3282 "Von Hippel-Lindau disease (3282)" "Von Hippel-Lindau disease"
* #prd3295 "Medullary sponge kidneys (3295)" "Medullary sponge kidneys"
* #prd3305 "Horse-shoe kidney (3305)" "Horse-shoe kidney"
* #prd3314 "Frasier syndrome (3314)" "Frasier syndrome"
* #prd3322 "Branchio-oto-renal syndrome (3322)" "Branchio-oto-renal syndrome"
* #prd3333 "Williams syndrome (3333)" "Williams syndrome"
* #prd3346 "Townes-Brocks syndrome (3346)" "Townes-Brocks syndrome"
* #prd3351 "Lawrence-Moon-Biedl / Bardet-Biedl syndrome (3351)" "Lawrence-Moon-Biedl / Bardet-Biedl syndrome"
* #prd3367 "Mitochondrial cytopathy (3367)" "Mitochondrial cytopathy"
* #prd3379 "Familial nephropathy (3379)" "Familial nephropathy"
* #prd3380 "Acute kidney injury (3380)" "Acute kidney injury"
* #prd3398 "Acute kidney injury due to hypovolaemia  (3398)" "Acute kidney injury due to hypovolaemia"
* #prd3403 "Acute kidney injury due to circulatory failure (3403)" "Acute kidney injury due to circulatory failure"
* #prd3419 "Acute kidney injury due to sepsis (3419)" "Acute kidney injury due to sepsis"
* #prd3426 "Acute kidney injury due to rhabdomyolysis (3426)" "Acute kidney injury due to rhabdomyolysis"
* #prd3435 "Acute kidney injury due to nephrotoxicity (3435)" "Acute kidney injury due to nephrotoxicity"
* #prd3442 "Acute cortical necrosis (3442)" "Acute cortical necrosis"
* #prd3457 "Acute pyelonephritis (3457)" "Acute pyelonephritis"
* #prd3461 "Kidney tumour (3461)" "Kidney tumour"
* #prd3474 "Renal cell carcinoma - histologically proven (3474)" "Renal cell carcinoma - histologically proven"
* #prd3488 "Transitional cell carcinoma - histologically proven (3488)" "Transitional cell carcinoma - histologically proven"
* #prd3490 "Wilms tumour - histologically proven (3490)" "Wilms tumour - histologically proven"
* #prd3501 "Mesoblastic nephroma - histologically proven (3501)" "Mesoblastic nephroma - histologically proven"
* #prd3517 "Single kidney identified in adulthood (3517)" "Single kidney identified in adulthood"
* #prd3529 "Chronic kidney disease (CKD) / chronic renal failure (CRF) caused by tumour nephrectomy (3529)" "Chronic kidney disease (CKD) / chronic renal failure (CRF) caused by tumour nephrectomy"
* #prd3538 "Chronic kidney disease (CKD) / chronic renal failure (CRF) due to traumatic loss of kidney (3538)" "Chronic kidney disease (CKD) / chronic renal failure (CRF) due to traumatic loss of kidney"
* #prd3540 "Chronic kidney disease (CKD) / chronic renal failure (CRF) due to donor nephrectomy (3540)" "Chronic kidney disease (CKD) / chronic renal failure (CRF) due to donor nephrectomy"
* #prd3555 "Chronic kidney disease (CKD) / chronic renal failure (CRF) - aetiology uncertain / unknown - no histology (3555)" "Chronic kidney disease (CKD) / chronic renal failure (CRF) - aetiology uncertain / unknown - no histology"
* #prd3564 "Chronic kidney disease (CKD) / chronic renal failure (CRF) - aetiology uncertain / unknown - histologically proven (3564)" "Chronic kidney disease (CKD) / chronic renal failure (CRF) - aetiology uncertain / unknown - histologically proven"
* #prd3572 "Haematuria and proteinuria - no histology (3572)" "Haematuria and proteinuria - no histology"
* #prd3604 "Nephrotic syndrome of childhood - steroid resistant - no histology (3604)" "Nephrotic syndrome of childhood - steroid resistant - no histology"
* #prd3615 "Nephrotic syndrome of childhood - no trial of steroids - no histology (3615)" "Nephrotic syndrome of childhood - no trial of steroids - no histology"
* #prd3627 "Renal cysts and diabetes syndrome (3627)" "Renal cysts and diabetes syndrome"
* #prd3636 "Chronic urate nephropathy - no histology (3636)" "Chronic urate nephropathy - no histology"
* #prd3643 "Chronic renal failure due to systemic infection (3643)" "Chronic renal failure due to systemic infection"
* #prd3658 "Renal coloboma syndrome (3658)" "Renal coloboma syndrome"
* #prd3662 "Hypercalcaemic nephropathy  (3662)" "Hypercalcaemic nephropathy"
* #prd3670 "Retroperitoneal fibrosis secondary to peri-aortitis (3670)" "Retroperitoneal fibrosis secondary to peri-aortitis"
* #prd3689 "Retroperitoneal fibrosis secondary to drugs (3689)" "Retroperitoneal fibrosis secondary to drugs"
* #prd3691 "Renal failure (3691)" "Renal failure"
* #prd3708 "Chronic renal failure (3708)" "Chronic renal failure"
* #prd3712 "Isolated haematuria - no histology (3712)" "Isolated haematuria - no histology"
* #prd3720 "Isolated proteinuria - no histology (3720)" "Isolated proteinuria - no histology"
* #prd3731 "Primary hyperoxaluria type III (3731)" "Primary hyperoxaluria type III"
* #prd3749 "Glomerulonephritis - no histology (3749)" "Glomerulonephritis - no histology"
* #prd3754 "Focal segmental glomerulosclerosis (FSGS) secondary to HIV  (3754)" "Focal segmental glomerulosclerosis (FSGS) secondary to HIV"
* #prd3765 "Focal segmental glomerulosclerosis (FSGS) secondary to lithium  (3765)" "Focal segmental glomerulosclerosis (FSGS) secondary to lithium"
* #prd3777 "Focal segmental glomerulosclerosis (FSGS) secondary to sickle cell (3777)" "Focal segmental glomerulosclerosis (FSGS) secondary to sickle cell"
* #prd3783 "Renal papillary necrosis caused by diabetes (3783)" "Renal papillary necrosis caused by diabetes"
* #prd3796 "Renal papillary necrosis caused by analgesics (3796)" "Renal papillary necrosis caused by analgesics"
* #prd3806 "Renal papillary necrosis caused by sickle cell (3806)" "Renal papillary necrosis caused by sickle cell"
* #prd3810 "Kidney stones due to ARPT deficiency (3810)" "Kidney stones due to ARPT deficiency"
* #prd3823 "Infiltration by lymphoma - histologically proven (3823)" "Infiltration by lymphoma - histologically proven"
* #prd3834 "Nephropathy due to pre-eclampsia (3834)" "Nephropathy due to pre-eclampsia"
* #prd3847 "Systemic vasculitis - ANCA negative - no histology (3847)" "Systemic vasculitis - ANCA negative - no histology"
* #prd3852 "Systemic vasculitis - ANCA positive - histologically proven (3852)" "Systemic vasculitis - ANCA positive - histologically proven"