CodeSystem: ChemotherapyRegimen
Title: "Chemotherapy regimen"
Description: "Chemotherapy regimen"

* ^status = #active
* ^publisher = "RKKP"
* ^date = "2022-07-15T00:00:00+02:00"
* ^contact[0].telecom[0].system = #url
* ^contact[0].telecom[0].value = "https://www.rkkp.dk/"
* ^content = #complete
* ^caseSensitive = false

* #abvd "ABVD" "ABVD / SKS: BWHA167"
* #copp "COPP" "COPP / SKS: BWHA156"
* #abvd/copp "ABVD/COPP" "ABVD/COPP"
* #acvbp "ACVBP" "ACVBP"
* #all_regime "ALL regime" "ALL regime"
* #adriamycin "Adriamycin" "Adriamycin"
* #bac "BAC" "BAC (Bendamustin Ara-c)"
* #bfm "BFM" "BFM"
* #cap "CAP" "CAP"
* #ccvp "CCVP" "CCVP"
* #chic "CHIC" "CHIC"
* #chlorambucil_vinblastin_procarb "Chlorambucil og Vinblastin og procarb" "Chlorambucil og Vinblastin og procarb"
* #cnsbonn "CNSBONN" "CNSBONN"
* #cns_matrix "CNS matrix" "CNS matrix"
* #cns_mvbp "CNS MVBP" "CNS MVBP"
* #cns_mvp "CNS MVP" "CNS MVP"
* #codox_m/ivac "CODOX-M/IVAC" "CODOX-M/IVAC"
* #comp "COMP" "COMP"
* #cope "COPE" "COPE"
* #cvbp "CVBP" "CVBP"
* #cvp "CVP" "CVP"
* #dexabeam "DexaBEAM" "DexaBEAM"
* #dhap "DHAP" "DHAP"
* #ecapp "ECAPP" "ECAPP"
* #epoch "EPOCH" "EPOCH"
* #eshap "ESHAP" "ESHAP"
* #fcd "FCD" "FCD"
* #fnd "FND" "FND"
* #gdp "GDP" "GDP"
* #gem_p_28 "GEM-P-28" "GEM-P-28"
* #gemox "GemOx" "GemOx"
* #hd_ara_c "HD-Ara-C" "HD-Ara-C"
* #hd_ctx "HD-CTX" "HD-CTX"
* #hd_ctx_vp16 "HD-CTX+VP16" "HD-CTX+VP16"
* #hd_vp16 "HD-VP16" "HD-VP16"
* #hd_mtx "HD-MTX" "HD-MTX"
* #hyper_cvad "Hyper-CVAD/IVAC" "Hyper-CVAD/IVAC"
* #ice "ICE" "ICE"
* #igev "IGEV" "IGEV"
* #ike "IKE" "IKE"
* #ive "IVE" "IVE"
* #it_behandling "IT-behandling" "IT-behandling"
* #macop_b "MACOP-B" "MACOP-b"
* #mantle_2 "Mantle 2" "Mantle 2"
* #maxi_mime "Maxi-MIME" "Maxi-MIME"
* #mini_beam "Mini-BEAM" "Mini-BEAM"
* #mini_chop "Mini-CHOP" "Mini-CHOP"
* #nopho "NOPHO" "NOPHO"
* #pix_etoposid_benda "Pix-etoposid-Benda" "Pix-etoposid-Benda"
* #peroral_cytostatika "Peroral cytostatika" "Peroral cytostatika"
* #smile "Smile" "Smile"
* #triangle_mantle "Triangle (Mantle)" "Triangle (Mantle)"
* #velbe "Velbe" "Velbe"
* #velcade "Velcade" "Velcade"
* #copdac "COPDAC" "COPDAC"
* #ebvp "EBVP" "EBVP"
* #ipe "IPE" "IPE"
* #oepa "OEPA" "OEPA"
* #oppa "OPPA" "OPPA"