ValueSet: GraftACLDKRR
Title: "Graft, ACL (DKRR)"
Description: "Graft, ACL (DKRR)"

* ^status = #active
* ^publisher = "RKKP"
* ^date = "2022-09-19T00:00:00+02:00"

* GraftCruciateLigaments#acl_repair_synthetic_reinforced "ACL repair med syntetisk forstærkning"
* GraftCruciateLigaments#bach-allo "BACH-Allo"
* GraftCruciateLigaments#bptb "BPTB"
* GraftCruciateLigaments#bptb-allo "BPTB-Allo"
* GraftCruciateLigaments#bqt "BQT"
* GraftCruciateLigaments#bqt-allo "BQT-Allo"
* GraftCruciateLigaments#direct_suture "Direkte sutur"
* GraftCruciateLigaments#double-bundle_bqt "Double-bundle BQT"
* GraftCruciateLigaments#double-bundle_st "Double-bundle ST"
* GraftCruciateLigaments#qt_without_bone_block "QT uden knogleklods"
* GraftCruciateLigaments#st_double "ST - Double"
* GraftCruciateLigaments#st_quadro "ST - Quadro"
* GraftCruciateLigaments#st_triple "ST - Triple"
* GraftCruciateLigaments#st/gr "ST/GR"
* GraftCruciateLigaments#st/gr_allo "ST/GR allo"
* GraftCruciateLigaments#synthetic "Syntetisk graft"
* GenericValues#other "Andet"