ValueSet: OpkodeUrinGenitalDUGA
Title: "Operationskode - Urin-inkontinens og genital prolaps (DUGA)"
Description: "Operationskode - Urin-inkontinens og genital prolaps (DUGA)"

* ^status = #active
* ^experimental = true
* ^publisher = "RKKP"
* ^date = "2024-02-14T00:00:00+02:00"

//Urin-inkontinens
* SKS#KKDG00  "KKDG00: Retropubisk supension af urinrør"
* SKS#KKDG30  "KKDG30: Abdominal uretrocystopeksi med slynge"
* SKS#KKDV22  "KKDV22: Uretroskopisk submukøs injektionsbehandling i urinrør"
* SKS#KLEG10  "KLEG10: Vaginal uretrocystopeksi med slynge"
* SKS#KLEG10A "KLEG10A: Vaginal uretrocystopeksi med slynge gennem foramen obturatum"
//Genital Prolaps  
* SKS#KLEF00  "KLEF00: Forreste kolporafi"
* SKS#KLEF00A "KLEF00A: Forreste kolporafi med meche"
* SKS#KLEF03  "KLEF03: Bageste kolporafi"
* SKS#KLEF03A "KLEF03A: Bageste kolporafi med meche"
* SKS#KLEF20  "KLEF20: Partiel kolpokleise"
* SKS#KLEF40  "KLEF40: Vaginal operation for enterocele"
* SKS#KLEF40A "KLEF40A: Vaginal operation for enterocele med meche"
* SKS#KLEF43  "KLEF43: Abdominal operation for enterocele"
* SKS#KLEF43A "KLEF43A: Abdominal operation for enterocele med meche"
* SKS#KLEF50  "KLEF50: Abdominal apikal kolpopeksi efter tidligere hysterektomi"
* SKS#KLEF50A "KLEF50A: Abdominal apikal kolpopeksi eft. tidl. hysterektomi m. meche"
* SKS#KLEF51  "KLEF51: Laparoskopisk apikal kolpopeksi efter tidligere hysterektomi"
* SKS#KLEF51A "KLEF51A: Laparoskop. apikal kolpopeksi eft.tidl. hysterektomi m. meche"
* SKS#KLEF53  "KLEF53: Vaginal apikal kolpopeksi efter tidligere hysterektomi"
* SKS#KLEF53A "KLEF53A: Vaginal apikal kolpopeksi efter tidl. hysterektomi med meche"
* SKS#KLEF53B "KLEF53B: Vaginal apikal kolpopeksi til det sakrospinøse ligament"
* SKS#KLEF60  "KLEF60: Vaginal lateral kolpopeksi"
* SKS#KLEF63  "KLEF63: Abdominal lateral kolpopeksi"
* SKS#KLCG20  "KLCG20: Hysteropeksi"
* SKS#KLCG21  "KLCG21: Laparoskopisk hysteropeksi"
* SKS#KLCG21A "KLCG21A: Laparoskopisk hysteropeksi med mesh"
* SKS#KLCD10  "KLCD10: Vaginal hysterektomi"
* SKS#KLDC10  "KLDC10: Resektion af livmoderhals"
* SKS#KLED00  "KLED00: Kolpektomi"
//Andet (sutur, robot mv.)
* SKS#KLEE00  "KLEE00: Sutur af vagina"
* SKS#KLFE00  "KLFE00: Sutur af vulva"
* SKS#KLFE96  "KLFE96: Anden rekonstruktion på vulva eller perineum"
* SKS#KJHC10  "KJHC10: Rekonstruktion af sphincter ani"
* SKS#KUKC02  "KUKC02: Cystoskopi"
* SKS#KZXF84A "KZXF84A: Ikke resorberbar sutur"
* SKS#KZXF84B "KZXF84B: Korttidsresorberbar sutur (< 3 uger)"
* SKS#KZXF84C "KZXF84C: Forsinket resorberbar sutur"
* SKS#KZXX00  "KZXX00: Anvendelse af robot"